fragment Audios on Query {
  audios(
    cursor: $cursor,
    limit: $limit,
    order: $order
  ) {
    pageInfo {
      ...PageInfo
    }
    edges {
      node {
        ...Audio
      }
      ...AudioEdges
    }
  }
}

fragment AudioEdges on AudioEdge {
  node {
    ...Audio
  }
}

fragment Audio on Audio {
  id
  name
  length
  url
  publishedAt
  likeCount
}

query Audios($cursor: Cursor!, $limit: Int, $order: [String!]) {
  ...Audios
#  version {
#    version
#  }
}
