fragment User on User {
    id
    name
    email
    photoURL
}

fragment CreateUser on Mutation {
    createUser(input: {id: $id, email: $email, name: $name, photoURL: $photoURL}) {
        ...User
    }
}

mutation CreateUser($id: ID!, $email: String!, $name: String!, $photoURL: String!) {
    ...CreateUser
}
